FROM openjdk:8
ADD target/java-container.jar /usr/src/myapp/
WORKDIR /usr/src/myapp
COPY start.sh /usr/src/myapp
RUN chmod +x /usr/src/myapp/start.sh
EXPOSE 8080

VOLUME /persistence

CMD ["/usr/src/myapp/start.sh"]
